### ISSUE TITLE
4. Title should be same as menu. The tab name should be 'List', 'Edit', 'Create'.

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/Anti-Corruption#4]
-Title should be same as menu. That means it should be dynamic. If change the menu name then title will be changed automatically.

![image](https://user-images.githubusercontent.com/52271735/61180767-6e953980-a63d-11e9-9514-a336fb032d7c.png)

**Comment by AnikaMollik** [comment]
Bug fixed
