### ISSUE TITLE
7. Anti Corruption-> Entry-> Create New -> There are few problems. Please see below's comment with image.

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/Anti-Corruption#7]
•	Picture is not displaying of particular employee after search by govt. id.
•	SPDS, LPDS link is not working. (Type- govt. id)
![image](https://user-images.githubusercontent.com/52271735/61181635-ef0e6700-a64a-11e9-87ab-706e5d2ae769.png)

•	When clicking on edit button Attachment document is not showing (for both type- Govt. id & Temp id)
•	When clicking on edit button picture is not showing (for type- Govt. id)
![image](https://user-images.githubusercontent.com/52271735/61181675-51fffe00-a64b-11e9-8a39-1ef7404fbb39.png)

**Comment by AnikaMollik** [comment]
Bug fixed
